kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-namespace-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - management.cattle.io
  resources:
  - "*"
  verbs:
  - updatepsa
